name: Deploy EC2

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Sync repo to EC2 and run deploy
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p /opt/seferverse-1789"
          rsync -az --delete --exclude ".git" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/seferverse-1789/
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd /opt/seferverse-1789/infra/scripts && STREAM_TOKEN='${{ secrets.STREAM_TOKEN }}' ALLOWED_ORIGINS='${{ secrets.ALLOWED_ORIGINS }}' NEXT_PUBLIC_EXPLORER_BASE='${{ secrets.NEXT_PUBLIC_EXPLORER_BASE }}' PRIVATE_KEY='${{ secrets.DEPLOY_PRIVATE_KEY }}' BASESCAN_API_KEY='${{ secrets.BASESCAN_API_KEY }}' ./deploy.sh"